body:
  - type: dropdown
    attributes:
      name: packageManager
      label: Package Manager
      description: Package Manager to use for installing applications
      defaultValue: Winget
      options:
        - Winget
        - Chocolatey
  - type: input
    attributes:
      name: stringsToDisplay
      label: Results display
      description: Controls how many results to display
      defaultValue: "10"
